# Generated by Django 3.0.7 on 2020-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
