# Generated by Django 3.0.7 on 2020-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
