# Generated by Django 3.0.7 on 2020-07-01 12:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200701_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
